overview_summary: |
  A Câmara dos Deputados é um dos lugares mais importantes do Brasil porque é onde os deputados federais, que são eleitos pelo povo, trabalham para criar as leis do país e fiscalizar o governo. Eles representam os interesses da população de todas as partes do Brasil.

  A Câmara tem 513 deputados, e cada estado tem um número de deputados proporcional à sua população. Isso significa que estados maiores, como São Paulo, têm mais deputados do que estados menores, como o Acre.

  Os deputados têm duas funções principais:
  1. Fazer as leis: Eles discutem e votam projetos que podem virar leis para o país.
  2. Fiscalizar o governo: Eles verificam se o Presidente e os ministros estão fazendo um bom trabalho e seguindo as regras.

  A Câmara dos Deputados faz parte do Congresso Nacional, junto com o Senado Federal. Juntos, eles decidem as leis e o futuro do Brasil.